languageCode = 'en-us'
title = 'The JSON Schema Registry | Sourcemeta One'
staticDir = [ './vendor/bootstrap-icons/font/fonts', './static' ]

[Params]
description = 'Sourcemeta One is the self-hosted JSON Schema registry for enterprise teams. Unify your schemas, monitor quality, and govern your entire API layer. Built by a member of the JSON Schema Technical Steering Committee.'
calendarURL = 'https://calendar.proton.me/bookings/guest#kZ6fS2qKjItr4XzCzSbllDsDL8W3S-vCJQ1aDozX9Z4='

[markup]
  [markup.highlight]
    style = 'swapoff'
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "vendor/bootstrap/js"
target = "assets/vendor/bootstrap/js"
