languageCode = 'en-us'
title = 'Sourcemeta'
staticDir = [ './vendor/bootstrap-icons/font/fonts', './static' ]

[Params]
description = 'The enterprise-grade, high-performance, self-hosted JSON Schema registry. Eliminate the complexity of operating schemas at scale.'

[markup]
  [markup.highlight]
    style = 'swapoff'

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "vendor/bootstrap/js"
target = "assets/vendor/bootstrap/js"
